---
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the
# server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andrew Pilsch's Professional Website
email: apilsch@tamu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Andrew Pilsch is an Associate Professor at Texas A&M in the English
  Department. He is broadly interested in rhetorical constructions of fate and
  human destiny in response to the radical technological changes of the digital.
  His research and pedagogy focuses on digital rhetoric, digital humanities,
  emerging media, and science fiction.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://andrew.pilsch.com"  # the base hostname & protocol for your site
twitter:
  username: oncomouse
github:
  username: oncomouse
social:
  name: Andrew Pilsch
  links:
    - https://twitter.com/oncomouse
    - http://orcid.org/0000-0002-4574-9387
    - https://scholar.google.com/citations?hl=en&user=QpZ-KiMAAAAJ
    - https://github.com/oncomouse

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - Rakefile
  - package.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - css/icons.css
  - font/
